<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Agregar texto' => '',
    'Alta de persona' => '',
    'Apellido' => '',
    'Comentario' => '',
    'Comentarios' => '',
    'Creado el' => '',
    'Creado por' => '',
    'Create Comentarios' => '',
    'Create Entradas' => '',
    'Create Persona' => '',
    'Create Portones' => '',
    'Create User' => '',
    'Create User Rol' => '',
    'Created At' => '',
    'Created By' => '',
    'Data' => '',
    'Descripcion' => '',
    'Description' => '',
    'Dni' => '',
    'Elegir Portón' => '',
    'Entradas' => '',
    'Fec.Creac.' => '',
    'Fecha desde' => '',
    'Fecha hasta' => '',
    'Foto' => '',
    'Habilitado' => '',
    'ID usuario' => '',
    'Idpersona' => '',
    'Idporton' => '',
    'Idvehiculo' => '',
    'Libro de guardia' => '',
    'Libros' => '',
    'Model' => '',
    'Model ID' => '',
    'Modificado el' => '',
    'Modificado por' => '',
    'Motivo' => '',
    'Name' => '',
    'Nombre' => '',
    'Nombre completo' => '',
    'Nombre2' => '',
    'Nueva Persona' => '',
    'Nueva entada al libro de guardia' => '',
    'Personas' => '',
    'Portones' => '',
    'Portones deshabilitados' => '',
    'Portón' => '',
    'Rol' => '',
    'Rule Name' => '',
    'Texto' => '',
    'Type' => '',
    'Updated At' => '',
    'Updated By' => '',
    'Usuarios del sistema' => '',
    'Create {modelClass}' => '@@Crear {modelClass}: @@',
    'Are you sure you want to delete this item?' => 'Seguro?',
    'Create' => 'Crear',
    'Delete' => 'Eliminar',
    'Email' => 'eMail',
    'ID' => 'ID',
    'Item Name' => 'Nombre de item',
    'Reset' => 'Limpiar',
    'Search' => 'Buscar',
    'Update' => 'Modificar',
    'Update {modelClass}: ' => 'Modificar {modelClass}: ',
    'User Rols' => 'Roles de usuario',
    'Username' => 'Usuario',
    'Users' => 'Usuarios',
    'description' => 'Descripción',
];
